# Generated by Django 4.2.4 on 2023-10-30 20:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
        ('Likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'product')},
        ),
    ]
