# Generated by Django 4.2.4 on 2023-10-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='residence',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
