# Generated by Django 4.2.4 on 2023-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
