# Generated by Django 4.2.4 on 2023-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuarios_groups_usuarios_is_active_usuarios_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default='default', max_length=40, unique=True),
        ),
    ]
