# Generated by Django 4.2.4 on 2023-10-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_email_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='residence',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
