# Generated by Django 4.2.4 on 2023-10-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usuarios_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='residence',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='address',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='city',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='department',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='details',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
