# Generated by Django 4.2.4 on 2023-10-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_usuarios_residence_usuarios_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='department',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='details',
            field=models.CharField(max_length=50),
        ),
    ]
