# Generated by Django 4.2.4 on 2023-10-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usuarios_address_alter_usuarios_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
