# Generated by Django 4.2.4 on 2023-10-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usuarios_address_alter_usuarios_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='first_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
