# Generated by Django 4.2.4 on 2023-10-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usuarios_first_name_usuarios_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
