# Generated by Django 4.2.4 on 2023-09-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table_Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_game',
            name='Table_GameId',
            field=models.BigAutoField(auto_created=True, default=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
