# Generated by Django 4.2.4 on 2023-09-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Table_Games', '0002_alter_table_game_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_game',
            name='ProductType',
        ),
    ]
