# Generated by Django 4.2.4 on 2023-09-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table_Games', '0002_alter_table_game_table_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_game',
            name='Table_GameId',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
