# Generated by Django 4.2.4 on 2023-08-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_availability'),
        ('Table_Games', '0002_table_game_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_game',
            name='Maker',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='table_game',
            name='Players_Number',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='table_game',
            name='Product',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
