# Generated by Django 4.2.4 on 2023-08-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_availability'),
        ('Table_Games', '0003_table_game_maker_table_game_players_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_game',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
