# Generated by Django 4.2.4 on 2023-08-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table_Games', '0004_alter_table_game_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_game',
            name='Maker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='table_game',
            name='Players_Number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='table_game',
            name='ProductType',
            field=models.CharField(choices=[('Viento', 'Viento'), ('Cuerda', 'Cuerda'), ('Percusión', 'Percusión'), ('Electrófonos', 'Electrófonos'), ('Idiófonos', 'Idiófonos')], max_length=20),
        ),
    ]
