# Generated by Django 4.2.4 on 2023-11-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
        ('Subcategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Price', models.PositiveIntegerField()),
                ('Description', models.CharField(max_length=10000)),
                ('ImageUrl', models.URLField(blank=True, max_length=1000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='./Products/Productimages/')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Discount', models.PositiveIntegerField()),
                ('ProductType', models.CharField(choices=[('Libro', 'Libro'), ('Instrumento Musical', 'Instrumento Musical'), ('Juego de mesa', 'Juego de mesa'), ('Tecnologia', 'Tecnologia')], default=False, max_length=20)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Categories.category')),
                ('Subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subcategories.subcategory')),
            ],
        ),
    ]
