# Generated by Django 4.2.4 on 2023-09-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Description', models.CharField(max_length=500)),
                ('ImageUrl', models.URLField(max_length=500)),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Discount', models.PositiveIntegerField(default=False)),
                ('ProductType', models.CharField(choices=[('Book', 'Book'), ('MusicalInstrument', 'Musical Instrument'), ('TableGames', 'Table Games'), ('Technology', 'Technology')], default=False, max_length=20)),
            ],
        ),
    ]
