# Generated by Django 4.2.4 on 2023-09-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductId',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductType',
            field=models.CharField(choices=[('Book', 'Book'), ('MusicalInstrument', 'Musical Instrument'), ('TableGames', 'Table Games'), ('Technology', 'Technology')], max_length=20),
        ),
    ]
