# Generated by Django 4.2.4 on 2023-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductType',
            field=models.CharField(choices=[('Libro', 'Libro'), ('Instrumento Musical', 'Instrumento Musical'), ('Juego de mesa', 'Juego de mesa'), ('Tecnologia', 'Tecnologia')], default=False, max_length=20),
        ),
    ]
