# Generated by Django 4.2.4 on 2023-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ImageUrl',
            field=models.URLField(max_length=500),
        ),
    ]
