# Generated by Django 4.2.4 on 2023-10-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
