# Generated by Django 4.2.4 on 2023-08-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
            ],
            bases=('Products.product',),
        ),
    ]
