# Generated by Django 4.2.4 on 2023-08-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegoDeMesa',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('jugadores', models.IntegerField()),
                ('edad_minima', models.IntegerField()),
            ],
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
            ],
            bases=('Products.product',),
        ),
    ]
