# Generated by Django 4.2.4 on 2023-08-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_juegodemesa_tecnologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='tecnologia',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='JuegoDeMesa',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Tecnologia',
        ),
    ]
