# Generated by Django 4.2.4 on 2023-10-17 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
        ('Subcategories', '0001_initial'),
        ('Products', '0009_alter_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categories.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Subcategories.subcategory'),
        ),
    ]
