# Generated by Django 4.2.4 on 2023-08-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_boook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boook',
        ),
    ]
