# Generated by Django 4.2.4 on 2023-10-17 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subcategories', '0002_alter_subcategory_category'),
        ('Categories', '0001_initial'),
        ('Products', '0010_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Categories.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subcategories.subcategory'),
        ),
    ]
