# Generated by Django 4.2.4 on 2023-08-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('Like', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Acentos',
        ),
    ]
