# Generated by Django 4.2.4 on 2023-08-17 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acentos', '0002_hola_delete_acentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hola',
            new_name='Book',
        ),
    ]
