# Generated by Django 4.2.4 on 2023-08-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acentos', '0005_remove_book_like_book_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
        migrations.AddField(
            model_name='book',
            name='Like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
