# Generated by Django 4.2.4 on 2023-08-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acentos', '0006_remove_book_url_book_like_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=False, upload_to='Acentos/images/'),
        ),
    ]
