# Generated by Django 4.2.4 on 2023-08-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acentos', '0008_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
