# Generated by Django 4.2.4 on 2023-08-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acentos', '0009_book_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
    ]
