# Generated by Django 4.2.4 on 2023-08-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acentos', '0010_remove_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='La',
            field=models.IntegerField(default=1),
        ),
    ]
