# Generated by Django 4.2.4 on 2023-09-03 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musical_Instrument',
            fields=[
                ('Musical_InstrumentId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('ProductType', models.CharField(choices=[('Viento', 'Viento'), ('Cuerda', 'Cuerda'), ('Percusión', 'Percusión'), ('Electrófonos', 'Electrófonos'), ('Idiófonos', 'Idiófonos')], max_length=20)),
                ('Brand', models.CharField(max_length=40)),
                ('Model', models.CharField(max_length=30)),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
