# Generated by Django 4.2.4 on 2023-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musical_Instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musical_instrument',
            name='ProductType',
            field=models.CharField(choices=[('Viento', 'Viento'), ('Cuerda', 'Cuerda'), ('Percusión', 'Percusión'), ('Electrófonos', 'Electrófonos'), ('Idiófonos', 'Idiófonos')], default=False, max_length=20),
        ),
    ]
