# Generated by Django 4.2.4 on 2023-08-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_imageurl'),
        ('Musical_Instruments', '0002_musical_instrument_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='musical_instrument',
            name='Brand',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='musical_instrument',
            name='Model',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='musical_instrument',
            name='product',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
