# Generated by Django 4.2.4 on 2023-09-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musical_Instruments', '0002_alter_musical_instrument_producttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musical_instrument',
            old_name='ProductType',
            new_name='MusicalInstrumentType',
        ),
    ]
