# Generated by Django 4.2.4 on 2023-08-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musical_Instruments', '0003_musical_instrument_brand_musical_instrument_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musical_instrument',
            old_name='product',
            new_name='Product',
        ),
    ]
