# Generated by Django 4.2.4 on 2023-09-03 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Authors', models.CharField(max_length=200)),
                ('Editorial', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=50)),
                ('YearPublication', models.IntegerField(default=False)),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
