# Generated by Django 4.2.4 on 2023-08-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='sin titulo', max_length=200)),
                ('Editorial', models.CharField(default='sin editorial', max_length=100)),
            ],
        ),
    ]
