# Generated by Django 4.2.4 on 2023-09-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Authors',
            field=models.CharField(max_length=200),
        ),
    ]
