# Generated by Django 4.2.4 on 2023-09-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.PositiveIntegerField(default=False, primary_key=True, serialize=False),
        ),
    ]
