# Generated by Django 4.2.4 on 2023-08-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_imageurl'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Language',
            field=models.CharField(default='español', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='Like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='YearPublication',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='product',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
