# Generated by Django 4.2.4 on 2023-09-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
