# Generated by Django 4.2.4 on 2023-09-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=200),
        ),
    ]
