# Generated by Django 4.2.4 on 2023-08-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_remove_book_like_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='product',
            new_name='Product',
        ),
    ]
