# Generated by Django 4.2.4 on 2023-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_book_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Authors',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
