# Generated by Django 4.2.4 on 2023-08-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Authors',
            field=models.CharField(max_length=200),
        ),
    ]
