# Generated by Django 4.2.4 on 2023-08-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_alter_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Product',
        ),
    ]
