# Generated by Django 4.2.4 on 2023-08-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_delete_boook'),
        ('Books', '0009_remove_book_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Product',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
