# Generated by Django 4.2.4 on 2023-11-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subcategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
