# Generated by Django 4.2.4 on 2023-09-09 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0003_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('TechnologyId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Characteristics', models.CharField(max_length=300)),
                ('Brand', models.CharField(max_length=50)),
                ('Model', models.CharField(default=False, max_length=50)),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
