# Generated by Django 4.2.4 on 2023-09-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technologys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='Model',
            field=models.CharField(max_length=50),
        ),
    ]
