# Generated by Django 4.2.4 on 2023-08-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technologys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='product',
            new_name='Product',
        ),
    ]
