# Generated by Django 4.2.4 on 2023-09-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technologys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='TechnologyId',
            field=models.BigAutoField(auto_created=True, default=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
