# Generated by Django 4.2.4 on 2023-08-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_availability'),
        ('Technologys', '0002_rename_product_technology_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
