# Generated by Django 4.2.4 on 2023-08-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technologys', '0003_alter_technology_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='Name',
            field=models.CharField(default=False, max_length=60),
        ),
    ]
