# Generated by Django 4.2.4 on 2023-08-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Technologys', '0005_alter_technology_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('technology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Technologys.technology')),
                ('RFC', models.CharField(max_length=50)),
            ],
            bases=('Technologys.technology',),
        ),
    ]
