# Generated by Django 4.2.4 on 2023-08-29 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technologys', '0006_libro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
